all_courses ="WITH ENROLMENTS AS (SELECT COURSE_ID,COUNT(USER_ID) AS ENROLLED_STUDENTS" \
   " FROM COURSEENROLMENTSTEST GROUP BY COURSE_ID)"\
" SELECT C.ID,C.NAME,C.STARTDATE,C.ENDDATE,C.TIME, C.DURATIONHOUR, C.OCCURANCES," \
   "CONCAT(T.LASTNAME, ', ', T.FIRSTNAME) AS TEACHER_NAME,R.NAME AS ROOM_NAME,E.ENROLLED_STUDENTS,"\
   "CASE WHEN R.CAPACITY - E.ENROLLED_STUDENTS < 1 THEN 'Full'ELSE 'Spot(s) available' END AS STATUS" \
" FROM COURSESTEST C LEFT JOIN TEACHERSTEST T ON T.ID = C.TEACHER_ID" \
" LEFT JOIN ROOMSTEST R ON R.ID = C.ROOM_ID LEFT JOIN ENROLMENTS E ON E.COURSE_ID = C.ID"